### ISSUE TITLE
Keep old Results

### ISSUE THREAD

**Issue by Elscha** [KernelHaven/KernelHaven#1]
Old analysis results should not automatically be overwritten. Except it was specified in configuration file, but it should not be the default. However, there does not exist an option to specify that behavior.

I suggest a similar approach as it is used for the log files.

**Comment by adam-sse** [comment]
Done. Relevant commits:
* 7fbce8a5bffa2ec436604c5663873fdf82a982c4 for PipelineAnalyis and AnalysisComponents
* https://github.com/KernelHaven/MetricHaven/commit/e03e7c525d8e3232a193b2f1589bdc9960eb5a4e for Metrics
