### ISSUE TITLE
Decouple analysis and saving analysis results

### ISSUE THREAD

**Issue by Elscha** [KernelHaven/KernelHaven#2]
Analysis and saving the analysis results should completely be decoupled.

Instead of writing Strings to an output stream, values should be saved to an extensible data model. Different writers should be specifiable in the configurations file.

**Comment by adam-sse** [comment]
This is now possible with the PipelineAnalysis and AnalysisComponent structure. However, a CsvWriter is currently always used.

TODO: Use ITableCollection to create output writer and instantiate it based on user configuration.

**Comment by adam-sse** [comment]
> TODO: Use ITableCollection to create output writer and instantiate it based on user configuration.

Done in 967d3a149721f643879e6a6e365ee8f4c4c4069f and 3e8886257e8aac111c465f8b94a7abbbfa25b16f
