### ISSUE TITLE
Excel Support

### ISSUE THREAD

**Issue by Elscha** [KernelHaven/KernelHaven#4]
Support for reading and writing excel documents (instead of csv files).
Suggestion as utility extension.

**Comment by Elscha** [comment]
* Reading is done by https://github.com/KernelHaven/IOUtils
* Proper writing is blocked by #2

**Comment by adam-sse** [comment]
We now have a proper table reading and writing interfaces ([`ITableReader`](https://github.com/KernelHaven/KernelHaven/blob/master/src/net/ssehub/kernel_haven/util/io/ITableReader.java), [`ITableWriter`](https://github.com/KernelHaven/KernelHaven/blob/master/src/net/ssehub/kernel_haven/util/io/ITableWriter.java), [`ITableCollection`](https://github.com/KernelHaven/KernelHaven/blob/master/src/net/ssehub/kernel_haven/util/io/ITableCollection.java).

I already ported your existing Excel stuff to this new structure ([`ExcelBook`](https://github.com/KernelHaven/IOUtils/blob/a3d0467bea4a84ee393ea1bfd922a8fdfa37ee03/src/net/ssehub/kernel_haven/io/excel/ExcelBook.java) is an `ITableCollection`, [`ExcelSheetReader`](https://github.com/KernelHaven/IOUtils/blob/a3d0467bea4a84ee393ea1bfd922a8fdfa37ee03/src/net/ssehub/kernel_haven/io/excel/ExcelSheetReader.java) is an `ITableReader`). The only thing missing now is writing support. To implement that, write an `ExcelSheetWriter` class that implements `ITableWriter`, and plug that into [here](https://github.com/KernelHaven/IOUtils/blob/a3d0467bea4a84ee393ea1bfd922a8fdfa37ee03/src/net/ssehub/kernel_haven/io/excel/ExcelBook.java#L126) (see `ExcelSheetReader`, [`CsvWriter`](https://github.com/KernelHaven/KernelHaven/blob/master/src/net/ssehub/kernel_haven/util/io/csv/CsvWriter.java) and [`TableRowMetadata`](https://github.com/KernelHaven/KernelHaven/blob/master/src/net/ssehub/kernel_haven/util/io/TableRowMetadata.java) for reference).

If your existing usage of the old, deprecated classes is ported, they can be removed.

**Comment by adam-sse** [comment]
> The only thing missing now is writing support.

Done in https://github.com/KernelHaven/IOUtils/commit/8dfd27cbd239acfed446f800471f1c69a97ad830
