### ISSUE TITLE
Check if `prepare_non_boolean.destination` points to a location inside of `source_tree`

### ISSUE THREAD

**Issue by Elscha** [KernelHaven/KernelHaven#8]
If `prepare_non_boolean.destination` points to a location inside of `source_tree`, KernelHaven will recursively copy all temporary files into a sub folder of `prepare_non_boolean.destination` until it crashes.
See `net.ssehub.kernel_haven.non_boolean.NonBooleanPreperation.copy(File, File)` @ Line 333.

**Comment by adam-sse** [comment]
https://github.com/KernelHaven/NonBooleanUtils/commit/358860636278339bf698d0f7dd47ea71f8c30840
